image:
  repository: your-docker-repo/django-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false

config:
  POSTGRES_DB:
  POSTGRES_USER:
  POSTGRES_PASSWORD:
  POSTGRES_HOST:
  POSTGRES_PORT: 5432
