image:
  repository: my-django-app
  tag: django-app
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

ingress:
  enabled: false

config:
  SECRET_KEY: "secret_key_for_django"
  POSTGRES_DB: django_db
  POSTGRES_USER: django_user
  POSTGRES_PASSWORD: django_password
  POSTGRES_HOST: localhost
  POSTGRES_PORT: 5432

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
