{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: {{ .project }}
  source:
    repoURL: {{ .source.repoURL }}
    path: {{ .source.path }}
    targetRevision: {{ .source.targetRevision }}
    helm:
      valueFiles:
        {{- range .source.helm.valueFiles }}
        - {{ . }}
        {{- end }}
      parameters:
        {{- range .source.helm.parameters }}
        - name: {{ .name | quote }}
          value: {{ .value | quote }}
        {{- end }}
        {{- if and (eq .name "django-app") $.Values.djangoApp.postgresHost }}
        - name: "config.POSTGRES_HOST"
          value: {{ $.Values.djangoApp.postgresHost | quote }}
        - name: "config.POSTGRES_PORT"
          value: {{ $.Values.djangoApp.postgresPort | quote }}
        {{- end }}
  destination:
    server: {{ .destination.server }}
    namespace: {{ .destination.namespace }}
  syncPolicy:
    automated:
      prune: {{ .syncPolicy.automated.prune }}
      selfHeal: {{ .syncPolicy.automated.selfHeal }}
---
{{- end }}
